name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull laguagu/cicd-pipeline:latest
    - name: Delete old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name cicd-pipeline-container laguagu/cicd-pipeline
    